version: "3"

# хранилища
volumes:
  pgdata:
    driver: local

services:
  db:
    container_name: postgres
    image: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "postgresql"
      POSTGRES_DB: "gbshop"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    expose:
      - 8000
    ports:
      - "80:8080"
    volumes:
      - ./static:/srv/web/static
      - ./media:/srv/web/media
      - ./logs:/srv/web/logs
      - ./docker/nginx:/etc/nginx/conf.d

    depends_on:
      - python

  python:
    container_name: python
    restart: always
    expose:
      - 8000
#    ports:
#      - "8000:8000"
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - .:/srv/web/
    depends_on:
      - db
#    command: python manage.py runserver 0.0.0.0:8080
    command: "gunicorn -c gunicorn.py gbshop.wsgi"
