# Generated by Django 2.0.8 on 2018-09-25 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='категория')),
                ('description', models.TextField(blank=True, verbose_name='описание категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='ProductLightSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='источник света')),
                ('description', models.TextField(blank=True, verbose_name='описание типа источника света')),
            ],
            options={
                'verbose_name': 'источник света',
                'verbose_name_plural': 'источники света',
            },
        ),
        migrations.CreateModel(
            name='ProductManufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='производитель')),
                ('description', models.TextField(blank=True, verbose_name='производитель устройства')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
            },
        ),
        migrations.CreateModel(
            name='ProductResolutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='разрешение')),
                ('description', models.TextField(blank=True, verbose_name='реальное разрешение устройства')),
            ],
            options={
                'verbose_name': 'разрешение',
                'verbose_name_plural': 'разрешения',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя')),
                ('image', models.ImageField(blank=True, upload_to='products_images', verbose_name='изображение')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество на складе')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMain.ProductCategories', verbose_name='категория')),
                ('light_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMain.ProductLightSources', verbose_name='источник света')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMain.ProductManufacturers', verbose_name='производитель')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMain.ProductResolutions', verbose_name='разрешение')),
            ],
            options={
                'verbose_name': 'проектор',
                'verbose_name_plural': 'проекторы',
            },
        ),
        migrations.CreateModel(
            name='ProductTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True, verbose_name='тип')),
                ('description', models.TextField(blank=True, verbose_name='описание типа устройства')),
            ],
            options={
                'verbose_name': 'тип',
                'verbose_name_plural': 'типы',
            },
        ),
        migrations.AddField(
            model_name='products',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appMain.ProductTypes', verbose_name='тип'),
        ),
    ]
