# Generated by Django 2.0.8 on 2018-09-25 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appAccounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
